create table if not exists ticket (
    id bigint generated by default as identity,
    body varchar(255),
    name varchar(255),
    subject varchar(255),
    primary key (id)
);
create table if not exists attachment (
    id uuid default random_uuid() not null,
    content blob,
    content_type varchar(255),
    filename varchar(255),
    ticket_id bigint,
    primary key (id),
    foreign key (ticket_id) references ticket
);
CREATE TABLE if not exists users (
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    PRIMARY KEY (username)
);
CREATE TABLE IF NOT EXISTS user_roles (
    user_role_id INTEGER GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_role_id),
    FOREIGN KEY (username) REFERENCES users(username)
    );

CREATE TABLE IF NOT EXISTS favorite_tickets (
    user_username VARCHAR(50) NOT NULL,
    ticket_id BIGINT NOT NULL,
    PRIMARY KEY (user_username, ticket_id),
    FOREIGN KEY (user_username) REFERENCES users(username),
    FOREIGN KEY (ticket_id) REFERENCES ticket(id)
    );
